# Generated by Django 2.0.4 on 2018-04-26 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SlackTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('social_users', models.ManyToManyField(to='social_django.UserSocialAuth')),
            ],
        ),
        migrations.AddField(
            model_name='slackbot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slack_github_deploy.SlackTeam'),
        ),
    ]
